allowBuilds:
  cpu-features: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  ssh2: set this to true or false
onlyBuiltDependencies:
  - bufferutil
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
  - utf-8-validate
